src/Covea.Assessment.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Covea.Assessment.Web.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

src/Covea.Assessment.Web/Controllers/RiskRatesController.cs
using Covea.Assessment.Domain.Entities;
using Covea.Assessment.Infra.Data.ORM.EF;
using Covea.Assessment.Web.Entity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Covea.Assessment.Web.Controllers
{
    public class RiskRatesController : Controller
    {
        private AssessmentDbContext db = new AssessmentDbContext();       
        

        // GET: RiskRates
        public ActionResult Index()
        {            
            return View("Index", "_Layout", db.RiskRates.ToList());
        }

		[HttpPost]
		public ActionResult Calculate(decimal pSumAssured, int pAge)
		{
            decimal _grossPremium = 0.0m;
            if (ModelState.IsValid)
            {
                List<RiskRates> listRiskRates = new List<RiskRates>();
                listRiskRates = db.RiskRates.ToList();

                decimal _sumAssuredFormated = decimal.Parse(pSumAssured.ToString("F3", CultureInfo.InvariantCulture));

                string _messageOutput;
                Rates _ratesOutput;
                if (!IsSumAssuredAgeValid(_sumAssuredFormated, pAge, listRiskRates, out _messageOutput, out _ratesOutput))
                {
                    return Json(new { success = false, message = _messageOutput }, JsonRequestBehavior.AllowGet);
                }
				else
				{
                    _grossPremium = CalculateMounthlyPremium(_ratesOutput);                    
                }
            }
            return View();
        }

        public bool IsSumAssuredAgeValid(decimal pSumAssured, int pAge, List<RiskRates> pListRiskRates, out string pMessageOutput, out Rates pRates)
		{
            decimal _sumAssured;
            decimal _rate;
            Rates _rates = new Rates();
            if (ModelState.IsValid)
			{                
                if (pAge > 31 && pAge <= 50)
				{
                    _sumAssured = pListRiskRates.Where(list => list.AgeBetween31and50!=null).Max(l => l.SumAssuredValue);                    
                    if (pSumAssured > _sumAssured)
					{
                        pMessageOutput = "The maximum sum assured for 31-50 years old is £" + _sumAssured.ToString();
                        pRates = null;
                        return false;
                    }
                    _rate = (decimal)pListRiskRates.Where(list => list.SumAssuredValue.Equals(pSumAssured)).First().AgeBetween31and50;

                }
                else if (pAge > 50)
                {
                    _sumAssured = pListRiskRates.Where(list => list.AgeMore50 != null).Max(l => l.SumAssuredValue);                    
                    if (pSumAssured > _sumAssured)
                    {
                        pMessageOutput = "The maximum sum assured for more 51 years old is £" + _sumAssured.ToString();
                        pRates = null;
                        return false;
                    }
                    _rate = (decimal)pListRiskRates.Where(list => list.SumAssuredValue.Equals(pSumAssured)).First().AgeMore50;
                }
                else
				{
                    _sumAssured = pSumAssured;
                    _rate = (decimal)pListRiskRates.Where(list => list.SumAssuredValue.Equals(pSumAssured)).First().AgeLess30;
                }
                _rates = new Rates
                {
                    SumAssured = _sumAssured,
                    Rate = _rate
                };
            }
            pRates = _rates;
            pMessageOutput = null;
			return true;
		}

        public decimal CalculateMounthlyPremium(Rates pRates)
		{
            decimal _riskPremium = 0.0m;
            decimal _renewalComission = 0.0m;
            decimal _netPremium = 0.0m;
            decimal _initialComission = 0.0m;
            decimal _grossPremium = 0.0m ;

            if (ModelState.IsValid)
			{
				_riskPremium = pRates.Rate * (pRates.SumAssured / 1000);
                _renewalComission = 0.03m * _riskPremium;
                _netPremium = _riskPremium + _renewalComission;
                _initialComission = _netPremium * 2.05m;
                _grossPremium = _netPremium * _initialComission;
            }
			
			return _grossPremium;
		}
	}
}

src/Covea.Assessment.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Covea.Assessment.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Covea.Assessment.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/Covea.Assessment.Web/Views/RiskRates/Index.cshtml
@model IEnumerable<Covea.Assessment.Domain.Entities.RiskRates>

<div class="col-md-12 col-sm-12 ">
	<div class="x_panel">
		<div class="x_title">
			<h2>Grade</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li>
					<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
			<div class="row">
				<div class="col-sm-12">
					<div class="card-box table-responsive">
						<table id="datatable" class="table table-striped table-bordered table-hover" style="width:100%">
							<thead>
								<tr>
									<th>Sum Assured</th>
									<th>Age <= 30</th>
									<th>Age Between 31 and 50 </th>
									<th>Age > 50 </th>
								</tr>
							</thead>


							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											£@Html.DisplayFor(modelItem => item.SumAssuredValue)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.AgeLess30)
										</td>
										<td>
											@if (item.AgeBetween31and50 == null)
											{
												<p>Not available</p>
											}
											else
											{
												@Html.DisplayFor(modelItem => item.AgeBetween31and50)
											}

										<td>
											@if (item.AgeMore50 == null)
											{
												<p>Not available</p>
											}
											else
											{
												@Html.DisplayFor(modelItem => item.AgeMore50)
											}

										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>


		<div>
			<div class="x_panel">
				<div class="alert alert-success" role="alert">
					<h2>Sum Assured</h2>
					<div class="clearfix"></div>
				</div>

				<div class="modal-body">
					<div class="form-horizontal">
						<div class="row">
							<div class="x_panel">
								<div class="x_title">
									<h2>@ViewBag.Title</h2>
									<ul class="nav navbar-right panel_toolbox">
										<li>
											<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
										</li>
										<li>
											<a class="close-link"><i class="fa fa-close"></i></a>
										</li>
									</ul>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<br />

									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="description">
											Sum Assured <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											<input type="text" id="txtSumAssured" />
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="details">
											Age <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											<input type="text" id="txtAge" />
										</div>
									</div>
									<div class="ln_solid"></div>

									<div class="item form-group">
										<div class="col-md-6 col-sm-6 offset-md-3">
											<input type="button" value="Submit" class="btn btn-success" onclick="Calc(document.getElementById('txtSumAssured').value, document.getElementById('txtAge').value)" />;
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>			
		</div>
	</div>
</div>

<script type="text/javascript">
	function Calc(pSumAssured, pAge) {
		debugger;

		if (pSumAssured == "") {
			toastr['error']('Sum Assured is required');
		}
		else if (pAge == "") {
			toastr['error']('Age is required');
		}

		var data = {
			pSumAssured: pSumAssured,
			pAge: pAge
		}

		$.ajax({
			async: true,
			url: '@Url.Action("Calculate", "RiskRates")',
			type: 'POST',
			data: data,
			datatype: 'json',
			//contentType: 'application/json; charset=utf-8',
			//success: function () {
				
			//}
			success: Message
		});
	}

	function Message(serverresult) {
		debugger;

		if (serverresult.success) {
			toastr.options = {
				"closeButton": false,
				"debug": false,
				"newestOnTop": false,
				"progressBar": false,
				"positionClass": "toast-top-right",
				"preventDuplicates": false,
				"onclick": null,
				"showDuration": "1500",
				"hideDuration": "1500",
				"timeOut": "5000",
				"extendedTimeOut": "1500",
				"showEasing": "swing",
				"hideEasing": "linear",
				"showMethod": "fadeIn",
				"hideMethod": "fadeOut"
			};

			toastr.success(
				serverresult.message,
				'Add',
				{
					timeOut: 1500,
					fadeOut: 1500
				}
			);
		}
		else {
			toastr['error'](serverresult.message);
		}
	}
</script>

src/Covea.Assessment.Web/Views/Shared/PartialLayout/_MenuLeft.cshtml
<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
	<div class="menu_section">
		<h3>General</h3>
		<ul class="nav side-menu">
			<li>
				<a><i class="fa fa-map"></i> Products <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li>@Html.ActionLink("Shirts", "Index", "Shirts")</li>
					<li>@Html.ActionLink("Ties", "Index", "Ties")</li>
					<li>@Html.ActionLink("Cufflinks", "Index", "Cufflinks")</li>
					<li>@Html.ActionLink("Carousel", "Index", "Products")</li>
					<li>@Html.ActionLink("Bag", "Index", "Bags")</li>

				</ul>
			</li>


		</ul>
	</div>
</div>
<!-- /sidebar menu -->

src/Covea.Assessment.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<!--TEMPLATE-->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<!-- Meta, title, CSS, favicons, etc. -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="~/Template/images/favicon.ico" type="image/ico" />

	<title>Covea Assessment</title>

	<link href="cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
	@*<link href="~/Content/toastr.css" rel="stylesheet" />
		<link href="~/Content/toastr.min.css" rel="stylesheet" />*@
	@Styles.Render("~/template/Styles")


</head>
<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Covea Assessment</span></a>
					</div>

					<div class="clearfix"></div>

					<br />

					<!-- /sidebar menu -->
					@Html.Partial("PartialLayout/_MenuLeft")

				</div>
			</div>

			<!-- page content -->
			<div class="right_col" role="main">
				@RenderBody()
			</div>
		</div>
	</div>

	@*<script src="~/Scripts/toastr.js"></script>
		<script src="~/Scripts/toastr.min.js"></script>*@
	@Scripts.Render("~/template/Scripts")

	@RenderSection("scripts", required: false)
</body>
</html>